### ISSUE TITLE
"normalizing" shapefiles

### ISSUE THREAD

**Issue by btengels** [btengels/optimaldistricts#2]
Some of our shapefiles are in correct long/lat units, and other are not. We need them all to have correct long/lat units so we can intersect them with the US census shapefiles. OR, we can normalize every state by it's smallest long/lat coordinate (and do the same with the census shapefiles), then do intersections to map census data to our precincts.

**Comment by btengels** [comment]
Fixed with GeoPandas' `to_crs()` function. Using `df.to_crs(epsg=4326)` for all shapefiles.

**Comment by ryanwmurray** [comment]
Are you pushing changes? I don't see them...

-Ryan
